#include <sourcemod>
#include <tf_econ_data>
#include "bot_personalities/generate_cosmetics_config.sp"
#include "bot_personalities/parse_cosmetics_config.sp"
#include "bot_personalities/add_cosmetics_config_comments.sp"
#include "bot_personalities/database/set_up_database.sp"

ConVar g_hCosmeticsConfigComments;
//ArrayList tempCosmetics;

public Plugin myinfo =
{
	name = "Bot Personalities",
	author = "Grimlord bone pulverizer",
	description = "Gives the tfbots a bit more personality",
	version = "1.0",
	url = "https://github.com/grimlordbonepulverizer/bot_personalities"
};

public void SetUpConvars()
{
	g_hCosmeticsConfigComments = CreateConVar("bp_cosmetics_config_comments", "1", "Enable or disable autogenerated comments in the cosmetics config file (1 = Enabled, 0 = Disabled)");
	
	AutoExecConfig(true, "bot_personalities");
}

public void OnPluginStart() 
{
	SetUpConvars();
	
	SetUpDatabase();
	GenerateCosmeticsConfig();
}

public void onAllPluginsLoaded()
{
	/*tempCosmetics = */ParseCosmeticsConfig();
}

public void OnAutoConfigsBuffered() 
{
	//if (g_hCosmeticsConfigComments.BoolValue) AddCosmeticsConfigComments(tempCosmetics);
	//delete tempCosmetics;
}
